### ISSUE TITLE
Could you provide the link to download the release package of the i-UR ADE extension (ZIP file)?

### ISSUE THREAD

**Issue by GabbySuwichaya** [3dcitydb/iur-ade-citydb#1]
Could you provide the link to download the release package of the i-UR ADE extension (ZIP file)?
The page  https://github.com/3dcitydb/iur-ade-citydb/releases   shows nothing ....

**Comment by yaozhihang** [comment]
Hi, there is currently no release package for the i-UR ADE extension, because it has a dependency of the upcoming [Importer/Exporter](https://github.com/3dcitydb/importer-exporter) version 4.3.0, which is still _work in progress_. A release package will be available by the end of Q1/2021.

**Comment by GabbySuwichaya** [comment]
Hi @yaozhihang, I see. 
Is there any older package that can be used with  Java-based 3D City DB importer/exporter (4.2.0) or with the 4.2.3 on Github page?  Would you be able to estimate the date of the release date?

**Comment by yaozhihang** [comment]
Unfortunately no, we don't have a package version being compatible with Importer/Exporter v4.2.x. I cannot promise an exact release date for the working version. As i mentioned, it will be available around the end of Q1 next year.

**Comment by GabbySuwichaya** [comment]
I see. Thank you very much for the information.

**Comment by clausnagel** [comment]
If you download the source code, you can manually run the extension through the class `UrbanRevitalizationADE`. And you can build an executable JAR using this class as main class (for instance, by adapting the `build.gradle` script). If you have some Java experience, this should be rather easy to do.

**Comment by clausnagel** [comment]
We just released two versions of the i-UR ADE extension: https://github.com/3dcitydb/iur-ade-citydb/releases

So, closing this issue.
