### ISSUE TITLE
link in READEME.MD is 404

### ISSUE THREAD

**Issue by Olivine-Ryo** [3dcitydb/iur-ade-citydb#2]
We cannot access link "https://www.kantei.go.jp/jp/singi/tiiki/toshisaisei/itoshisaisei/iur".

**Comment by clausnagel** [comment]
Thanks for reporting. The website is not under our control. It seems that it has been moved to https://www.chisou.go.jp/tiiki/toshisaisei/itoshisaisei/iur. I have adapted the readme file accordingly.
